version: '3.9'
services:
  redis:
    image: redis:6.0.9-alpine
    container_name: mutant_redis
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mutant_recruitment_development
    command: -p 5435
    ports:
      - "5435:5435"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

  testdb:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mutant_recruitment_test
    command: -p 5436
    ports:
      - "5436:5435"
    expose:
      - "5435"
    volumes:
      - testdb_data:/var/lib/postgresql/data:delegated

volumes:
  db_data:
  testdb_data:
